@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.2.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Sep 11 14:37:17 +0700 2025
REM SW Build 3788238 on Tue Feb 21 20:00:34 MST 2023
REM
REM IP Build 3783773 on Tue Feb 21 23:41:56 MST 2023
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_mul_poly_matrix_behav -key {Behavioral:sim_1:Functional:tb_mul_poly_matrix} -tclbatch tb_mul_poly_matrix.tcl -view C:/Hung/Viettel/Stage2/ML-KEM/mul_poly/mul_matrix/tb_mul_12bit_behav.wcfg -view C:/Hung/Viettel/Stage2/ML-KEM/mul_poly/mul_matrix/tb_mul_poly_matrix_behav.wcfg -log simulate.log"
call xsim  tb_mul_poly_matrix_behav -key {Behavioral:sim_1:Functional:tb_mul_poly_matrix} -tclbatch tb_mul_poly_matrix.tcl -view C:/Hung/Viettel/Stage2/ML-KEM/mul_poly/mul_matrix/tb_mul_12bit_behav.wcfg -view C:/Hung/Viettel/Stage2/ML-KEM/mul_poly/mul_matrix/tb_mul_poly_matrix_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
